services:
  NetEngKit:
    build: .
    image: netengkit:latest
    container_name: NetEngKit
    network_mode: host
    env_file:
      - path: .env
        required: false
    environment:
      - PORT=${PORT:-8080}
      - NETENGKIT_HOSTS=${NETENGKIT_HOSTS:-*}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: unless-stopped
