// Shared DNS provider registry. Loaded as a plain <script> before Babel components.
// Exposes window.DOH_PROVIDERS — consumed by DNSLookup, DohDotConfig, IPv6SubnetCalc.
//
// Fields:
//   key          - unique string identifier
//   name         - display name (EN)
//   desc         - one-line English description
//   ips_v4       - IPv4 addresses [primary, secondary]  ([] if none)
//   ips_v6       - IPv6 addresses [primary, secondary]  ([] if none)
//   doh_url      - DoH HTTPS endpoint; null = no public DoH
//   doh_json     - true: Google-style /resolve JSON (no Accept header needed)
//                  false: RFC 8484 JSON (needs Accept: application/dns-json)
//   dot_hostname - hostname for DoT TLS SNI
//   pin          - SPKI pin base64 string ('' if none)

window.DOH_PROVIDERS = [
  {
    key: 'google',
    name: 'Google Public DNS',
    desc: 'Google\'s reliable public resolver',
    ips_v4: ['8.8.8.8', '8.8.4.4'],
    ips_v6: ['2001:4860:4860::8888', '2001:4860:4860::8844'],
    doh_url: 'https://dns.google/resolve',
    doh_json: true,
    dot_hostname: 'dns.google',
    pin: '',
  },
  {
    key: 'cloudflare',
    name: 'Cloudflare (1.1.1.1)',
    desc: 'Privacy-first resolver by Cloudflare',
    ips_v4: ['1.1.1.1', '1.0.0.1'],
    ips_v6: ['2606:4700:4700::1111', '2606:4700:4700::1001'],
    doh_url: 'https://cloudflare-dns.com/dns-query',
    doh_json: false,
    dot_hostname: 'cloudflare-dns.com',
    pin: 'yio4yV4fA3TUs2V5cWbWpHH/3dF48z68MhBsk4c/wH8=',
  },
  {
    key: 'cloudflare_family',
    name: 'Cloudflare for Families',
    desc: 'Cloudflare with malware and adult content blocking',
    ips_v4: ['1.1.1.3', '1.0.0.3'],
    ips_v6: ['2606:4700:4700::1113', '2606:4700:4700::1003'],
    doh_url: 'https://family.cloudflare-dns.com/dns-query',
    doh_json: false,
    dot_hostname: 'family.cloudflare-dns.com',
    pin: '',
  },
  {
    key: 'quad9',
    name: 'Quad9 — Secured (9.9.9.9)',
    desc: 'Security-focused with malware blocking',
    ips_v4: ['9.9.9.9', '149.112.112.112'],
    ips_v6: ['2620:fe::fe', '2620:fe::9'],
    doh_url: 'https://dns.quad9.net/dns-query',
    doh_json: false,
    dot_hostname: 'dns.quad9.net',
    pin: '',
  },
  {
    key: 'quad9_unsecured',
    name: 'Quad9 — Unsecured',
    desc: 'Quad9 without malware filtering',
    ips_v4: ['9.9.9.10', '149.112.112.10'],
    ips_v6: ['2620:fe::10', '2620:fe::fe:10'],
    doh_url: 'https://dns11.quad9.net/dns-query',
    doh_json: false,
    dot_hostname: 'dns11.quad9.net',
    pin: '',
  },
  {
    key: 'adguard',
    name: 'AdGuard DNS',
    desc: 'Ad and tracker blocking resolver',
    ips_v4: ['94.140.14.14', '94.140.15.15'],
    ips_v6: ['2a10:50c0::ad1:ff', '2a10:50c0::ad2:ff'],
    doh_url: 'https://dns.adguard-dns.com/resolve',
    doh_json: true,
    dot_hostname: 'dns.adguard-dns.com',
    pin: '',
  },
  {
    key: 'adguard_family',
    name: 'AdGuard Family',
    desc: 'AdGuard DNS with adult content blocking',
    ips_v4: ['94.140.14.15', '94.140.15.16'],
    ips_v6: ['2a10:50c0::bad1:ff', '2a10:50c0::bad2:ff'],
    doh_url: 'https://family.adguard-dns.com/resolve',
    doh_json: true,
    dot_hostname: 'family.adguard-dns.com',
    pin: '',
  },
  {
    key: 'opendns',
    name: 'OpenDNS Home (Cisco)',
    desc: 'Cisco OpenDNS with phishing and malware filtering',
    ips_v4: ['208.67.222.222', '208.67.220.220'],
    ips_v6: ['2620:119:35::35', '2620:119:53::53'],
    doh_url: 'https://doh.opendns.com/dns-query',
    doh_json: false,
    dot_hostname: 'doh.opendns.com',
    pin: '',
  },
  {
    key: 'opendns_family',
    name: 'OpenDNS FamilyShield',
    desc: 'OpenDNS with adult content blocking',
    ips_v4: ['208.67.222.123', '208.67.220.123'],
    ips_v6: [],
    doh_url: 'https://doh.familyshield.opendns.com/dns-query',
    doh_json: false,
    dot_hostname: 'doh.familyshield.opendns.com',
    pin: '',
  },
  {
    key: 'cleanbrowsing',
    name: 'CleanBrowsing Family',
    desc: 'Family-safe DNS with adult content filtering',
    ips_v4: ['185.228.168.168', '185.228.169.168'],
    ips_v6: ['2a0d:2a00:1::', '2a0d:2a00:2::'],
    doh_url: 'https://doh.cleanbrowsing.org/doh/family-filter/',
    doh_json: false,
    dot_hostname: 'doh.cleanbrowsing.org',
    pin: '',
  },
  {
    key: 'nextdns',
    name: 'NextDNS',
    desc: 'Configurable filtering DNS (profile-based IPs)',
    ips_v4: [],
    ips_v6: [],
    doh_url: 'https://dns.nextdns.io/dns-query',
    doh_json: false,
    dot_hostname: 'dns.nextdns.io',
    pin: '',
  },
  {
    key: 'mullvad',
    name: 'Mullvad DNS',
    desc: 'No-log privacy resolver by Mullvad VPN',
    ips_v4: ['194.242.2.2', '194.242.2.3'],
    ips_v6: ['2a07:e340::2', '2a07:e340::3'],
    doh_url: 'https://dns.mullvad.net/dns-query',
    doh_json: false,
    dot_hostname: 'dns.mullvad.net',
    pin: '',
  },
  {
    key: 'dns0eu',
    name: 'dns0.eu (EU/GDPR)',
    desc: 'European resolver, GDPR-compliant, no logging',
    ips_v4: ['193.110.81.0', '185.253.5.0'],
    ips_v6: ['2a0f:fc80::', '2a0f:fc81::'],
    doh_url: 'https://dns0.eu/dns-query',
    doh_json: false,
    dot_hostname: 'dns0.eu',
    pin: '',
  },
  {
    key: 'yandex',
    name: 'Yandex DNS',
    desc: 'Yandex public resolver',
    ips_v4: ['77.88.8.8', '77.88.8.1'],
    ips_v6: ['2a02:6b8::feed:bad', '2a02:6b8:0:1::feed:bad'],
    doh_url: null,
    doh_json: false,
    dot_hostname: 'common.dot.dns.yandex.net',
    pin: '',
  },
  {
    key: 'yandex_safe',
    name: 'Yandex Safe',
    desc: 'Yandex DNS with malware and fraud blocking',
    ips_v4: ['77.88.8.88', '77.88.8.2'],
    ips_v6: ['2a02:6b8::feed:a11', '2a02:6b8:0:1::feed:a11'],
    doh_url: null,
    doh_json: false,
    dot_hostname: 'safe.dot.dns.yandex.net',
    pin: '',
  },
  {
    key: 'yandex_family',
    name: 'Yandex Family',
    desc: 'Yandex DNS with adult content blocking',
    ips_v4: ['77.88.8.7', '77.88.8.3'],
    ips_v6: ['2a02:6b8::feed:bad1', '2a02:6b8:0:1::feed:bad1'],
    doh_url: null,
    doh_json: false,
    dot_hostname: 'family.dot.dns.yandex.net',
    pin: '',
  },
];
